<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\UserController' shared autowired service.

return $this->services['AppBundle\\Controller\\UserController'] = new \AppBundle\Controller\UserController();
