twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    number_format:
        thousands_separator: ' '
        decimal_point: ','
    globals:
        locales: '%app_locales%'
    form_themes: ['bootstrap_4_layout.html.twig']