<?php

namespace AppBundle\Repository;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends \Doctrine\ORM\EntityRepository
{
}
