<?php

namespace AppBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
    function getChildAndParent($id)
    {
        $query = $this->createQueryBuilder('tache')
            ->having('tache.id ='.$id)
            ->orHaving('dim.parent ='.$id);

        return $query->getQuery()->getResult();
    }
}
