<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExceptItself($id)
    {
        return $this->createQueryBuilder('t')
            ->where('t.id != :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
