<?php

namespace AppBundle\Repository;

/**
 * WorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerRepository extends \Doctrine\ORM\EntityRepository
{
}
