<?php

namespace App\Repository;

use App\Entity\Project;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
